//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS_Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITS_Studio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Actions_go_down_icon {
            get {
                object obj = ResourceManager.GetObject("Actions_go_down_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Actions_go_next_icon {
            get {
                object obj = ResourceManager.GetObject("Actions_go_next_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Actions_go_previous_icon {
            get {
                object obj = ResourceManager.GetObject("Actions_go_previous_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Actions_go_up_icon {
            get {
                object obj = ResourceManager.GetObject("Actions_go_up_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Actions_list_add_icon {
            get {
                object obj = ResourceManager.GetObject("Actions_list_add_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Actions_tools_wizard_icon {
            get {
                object obj = ResourceManager.GetObject("Actions_tools_wizard_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Actions_view_refresh_icon_32_32 {
            get {
                object obj = ResourceManager.GetObject("Actions_view_refresh_icon_32_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 不存在 的當地語系化字串。
        /// </summary>
        internal static string AdditionalFeatureMsg_CN {
            get {
                return ResourceManager.GetString("AdditionalFeatureMsg_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} doesn&apos;t exist. 的當地語系化字串。
        /// </summary>
        internal static string AdditionalFeatureMsg_EN {
            get {
                return ResourceManager.GetString("AdditionalFeatureMsg_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 附加功能 的當地語系化字串。
        /// </summary>
        internal static string AdditionalFeatureTitle_CN {
            get {
                return ResourceManager.GetString("AdditionalFeatureTitle_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Additional feature 的當地語系化字串。
        /// </summary>
        internal static string AdditionalFeatureTitle_EN {
            get {
                return ResourceManager.GetString("AdditionalFeatureTitle_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Adobe_PDF_Document_icon16_16 {
            get {
                object obj = ResourceManager.GetObject("Adobe_PDF_Document_icon16_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ajax_loader {
            get {
                object obj = ResourceManager.GetObject("ajax_loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Back_icon_32_32 {
            get {
                object obj = ResourceManager.GetObject("Arrow_Back_icon_32_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Back_icon_64_64 {
            get {
                object obj = ResourceManager.GetObject("Arrow_Back_icon_64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap BridgePic1 {
            get {
                object obj = ResourceManager.GetObject("BridgePic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap c_model_64_64 {
            get {
                object obj = ResourceManager.GetObject("c_model_64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        internal static string Cancel_CN {
            get {
                return ResourceManager.GetString("Cancel_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string Cancel_EN {
            get {
                return ResourceManager.GetString("Cancel_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap cancel_icon {
            get {
                object obj = ResourceManager.GetObject("cancel_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Channel數量不符!! 的當地語系化字串。
        /// </summary>
        internal static string ChannelErr_CN {
            get {
                return ResourceManager.GetString("ChannelErr_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Channel size is not mapped !! 的當地語系化字串。
        /// </summary>
        internal static string ChannelErr_EN {
            get {
                return ResourceManager.GetString("ChannelErr_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap chart_icon {
            get {
                object obj = ResourceManager.GetObject("chart_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap cleaning {
            get {
                object obj = ResourceManager.GetObject("cleaning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap clicknrun {
            get {
                object obj = ResourceManager.GetObject("clicknrun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 裝置與Hex檔案的CRC不符 的當地語系化字串。
        /// </summary>
        internal static string CRCDiff_CN {
            get {
                return ResourceManager.GetString("CRCDiff_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CRC are differts between the device and the hex file 的當地語系化字串。
        /// </summary>
        internal static string CRCDiff_EN {
            get {
                return ResourceManager.GetString("CRCDiff_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Dark_Documents_icon {
            get {
                object obj = ResourceManager.GetObject("Dark_Documents_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Dark_Play_1_Pressed_icon_48_48 {
            get {
                object obj = ResourceManager.GetObject("Dark_Play_1_Pressed_icon_48_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 裝置在BL模式. 的當地語系化字串。
        /// </summary>
        internal static string DevBLMode_CN {
            get {
                return ResourceManager.GetString("DevBLMode_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device is BL mode. 的當地語系化字串。
        /// </summary>
        internal static string DevBLMode_EN {
            get {
                return ResourceManager.GetString("DevBLMode_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 裝置錯誤!! 的當地語系化字串。
        /// </summary>
        internal static string DeviceStatusErr_CN {
            get {
                return ResourceManager.GetString("DeviceStatusErr_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There&apos;s something wrong with DeviceStatus!! 的當地語系化字串。
        /// </summary>
        internal static string DeviceStatusErr_EN {
            get {
                return ResourceManager.GetString("DeviceStatusErr_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap disconnect {
            get {
                object obj = ResourceManager.GetObject("disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Do_Not_Touch {
            get {
                object obj = ResourceManager.GetObject("Do_Not_Touch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Document_Chart_icon {
            get {
                object obj = ResourceManager.GetObject("Document_Chart_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Document_Copy_icon {
            get {
                object obj = ResourceManager.GetObject("Document_Copy_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Document_Edit_icon {
            get {
                object obj = ResourceManager.GetObject("Document_Edit_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Document_Gant_Chart_icon_64_64 {
            get {
                object obj = ResourceManager.GetObject("Document_Gant_Chart_icon_64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Document_icon {
            get {
                object obj = ResourceManager.GetObject("Document_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Document_Line_Chart_icon {
            get {
                object obj = ResourceManager.GetObject("Document_Line_Chart_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Document_Preview_icon {
            get {
                object obj = ResourceManager.GetObject("Document_Preview_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Documents_icon {
            get {
                object obj = ResourceManager.GetObject("Documents_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Documents_icon16_16 {
            get {
                object obj = ResourceManager.GetObject("Documents_icon16_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Ecommerce_Barcode_Scanner_icon {
            get {
                object obj = ResourceManager.GetObject("Ecommerce_Barcode_Scanner_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Ecommerce_Barcode_Scanner_icon128_128 {
            get {
                object obj = ResourceManager.GetObject("Ecommerce_Barcode_Scanner_icon128_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Ecommerce_Barcode_Scanner_icon64_64 {
            get {
                object obj = ResourceManager.GetObject("Ecommerce_Barcode_Scanner_icon64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Encryption {
            get {
                object obj = ResourceManager.GetObject("Encryption", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap FAIL {
            get {
                object obj = ResourceManager.GetObject("FAIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap File_Open_icon {
            get {
                object obj = ResourceManager.GetObject("File_Open_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap functuib_gen_64_64 {
            get {
                object obj = ResourceManager.GetObject("functuib_gen_64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap gen_ini {
            get {
                object obj = ResourceManager.GetObject("gen_ini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Graphics_Painting_icon {
            get {
                object obj = ResourceManager.GetObject("Graphics_Painting_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap green_ok_icon {
            get {
                object obj = ResourceManager.GetObject("green_ok_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap grid {
            get {
                object obj = ResourceManager.GetObject("grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap hex_to_ili_64_64 {
            get {
                object obj = ResourceManager.GetObject("hex_to_ili_64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap HoverCircle {
            get {
                object obj = ResourceManager.GetObject("HoverCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap HoverCircle2 {
            get {
                object obj = ResourceManager.GetObject("HoverCircle2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_low_connection_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_low_connection_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_no_connection_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_no_connection_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_signal_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_signal_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_strong_signal_24 {
            get {
                object obj = ResourceManager.GetObject("icons8_strong_signal_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ILIlogo {
            get {
                object obj = ResourceManager.GetObject("ILIlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap industry_icon {
            get {
                object obj = ResourceManager.GetObject("industry_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 不正確的檔案格式,{0}是不正確的! 的當地語系化字串。
        /// </summary>
        internal static string InvalidFileFormat_CN {
            get {
                return ResourceManager.GetString("InvalidFileFormat_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid file format.,{0} is invalid! 的當地語系化字串。
        /// </summary>
        internal static string InvalidFileFormat_EN {
            get {
                return ResourceManager.GetString("InvalidFileFormat_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ITS_Tool_Legal {
            get {
                object obj = ResourceManager.GetObject("ITS_Tool_Legal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap LH1_Play_icon128_128 {
            get {
                object obj = ResourceManager.GetObject("LH1_Play_icon128_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap LH1_Play_icon16_16 {
            get {
                object obj = ResourceManager.GetObject("LH1_Play_icon16_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap LH1_Play_icon64_64 {
            get {
                object obj = ResourceManager.GetObject("LH1_Play_icon64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap load {
            get {
                object obj = ResourceManager.GetObject("load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 讀取TPL失敗! 的當地語系化字串。
        /// </summary>
        internal static string LoadingTPLFailure_CN {
            get {
                return ResourceManager.GetString("LoadingTPLFailure_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading TPL was failure! 的當地語系化字串。
        /// </summary>
        internal static string LoadingTPLFailure_EN {
            get {
                return ResourceManager.GetString("LoadingTPLFailure_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀取Panel資訊完成 的當地語系化字串。
        /// </summary>
        internal static string LoadPanelFinish_CN {
            get {
                return ResourceManager.GetString("LoadPanelFinish_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Load Panel Info Finish. 的當地語系化字串。
        /// </summary>
        internal static string LoadPanelFinish_EN {
            get {
                return ResourceManager.GetString("LoadPanelFinish_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MCU版本不符!! 的當地語系化字串。
        /// </summary>
        internal static string MCUErr_CN {
            get {
                return ResourceManager.GetString("MCUErr_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MCU is not mapped !! 的當地語系化字串。
        /// </summary>
        internal static string MCUErr_EN {
            get {
                return ResourceManager.GetString("MCUErr_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap microscope {
            get {
                object obj = ResourceManager.GetObject("microscope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Mimetypes_cmd {
            get {
                object obj = ResourceManager.GetObject("Mimetypes_cmd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap new_file_icon {
            get {
                object obj = ResourceManager.GetObject("new_file_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 否 的當地語系化字串。
        /// </summary>
        internal static string No_CN {
            get {
                return ResourceManager.GetString("No_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No 的當地語系化字串。
        /// </summary>
        internal static string No_EN {
            get {
                return ResourceManager.GetString("No_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Normal_Home_icon {
            get {
                object obj = ResourceManager.GetObject("Normal_Home_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap page_process_icon {
            get {
                object obj = ResourceManager.GetObject("page_process_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap panel_64_64 {
            get {
                object obj = ResourceManager.GetObject("panel_64_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap PASS {
            get {
                object obj = ResourceManager.GetObject("PASS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入密碼： 的當地語系化字串。
        /// </summary>
        internal static string Password_Cn {
            get {
                return ResourceManager.GetString("Password_Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the password :  的當地語系化字串。
        /// </summary>
        internal static string Password_En {
            get {
                return ResourceManager.GetString("Password_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼輸入錯誤 的當地語系化字串。
        /// </summary>
        internal static string PasswordErr_Cn {
            get {
                return ResourceManager.GetString("PasswordErr_Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Incorrect password 的當地語系化字串。
        /// </summary>
        internal static string PasswordErr_En {
            get {
                return ResourceManager.GetString("PasswordErr_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您輸入的密碼：{0} 的當地語系化字串。
        /// </summary>
        internal static string PasswordTip_Cn {
            get {
                return ResourceManager.GetString("PasswordTip_Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The password you entered: {0} 的當地語系化字串。
        /// </summary>
        internal static string PasswordTip_En {
            get {
                return ResourceManager.GetString("PasswordTip_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Pause_Normal_Red_icon {
            get {
                object obj = ResourceManager.GetObject("Pause_Normal_Red_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Pencil_icon {
            get {
                object obj = ResourceManager.GetObject("Pencil_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 手寫筆協議版本不符!! 的當地語系化字串。
        /// </summary>
        internal static string PenTypeErr_CN {
            get {
                return ResourceManager.GetString("PenTypeErr_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PenType is not mapped!! 的當地語系化字串。
        /// </summary>
        internal static string PenTypeErr_EN {
            get {
                return ResourceManager.GetString("PenTypeErr_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PID 不符!! 的當地語系化字串。
        /// </summary>
        internal static string PIDErr_CN {
            get {
                return ResourceManager.GetString("PIDErr_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PID not mapping!! 的當地語系化字串。
        /// </summary>
        internal static string PIDErr_EN {
            get {
                return ResourceManager.GetString("PIDErr_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Play_Pressed_icon {
            get {
                object obj = ResourceManager.GetObject("Play_Pressed_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 處理中，請稍候... 的當地語系化字串。
        /// </summary>
        internal static string ProcessingTip_Cn {
            get {
                return ResourceManager.GetString("ProcessingTip_Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Processing, please wait... 的當地語系化字串。
        /// </summary>
        internal static string ProcessingTip_En {
            get {
                return ResourceManager.GetString("ProcessingTip_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Profile 版本不符!! 的當地語系化字串。
        /// </summary>
        internal static string ProfileErr_CN {
            get {
                return ResourceManager.GetString("ProfileErr_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Profile Version is not mapped!! 的當地語系化字串。
        /// </summary>
        internal static string ProfileErr_EN {
            get {
                return ResourceManager.GetString("ProfileErr_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 協議版本不符!! 的當地語系化字串。
        /// </summary>
        internal static string ProtocolErr_CN {
            get {
                return ResourceManager.GetString("ProtocolErr_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Protocol not mapping!! 的當地語系化字串。
        /// </summary>
        internal static string ProtocolErr_EN {
            get {
                return ResourceManager.GetString("ProtocolErr_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap scrolldowngesture {
            get {
                object obj = ResourceManager.GetObject("scrolldowngesture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Search_icon {
            get {
                object obj = ResourceManager.GetObject("Search_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Small_arrow_left_fast_rewind_icon {
            get {
                object obj = ResourceManager.GetObject("Small_arrow_left_fast_rewind_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Small_arrow_right_fast_forward_icon {
            get {
                object obj = ResourceManager.GetObject("Small_arrow_right_fast_forward_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Small_arrow_up_icon {
            get {
                object obj = ResourceManager.GetObject("Small_arrow_up_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Stop_Normal_Red_icon {
            get {
                object obj = ResourceManager.GetObject("Stop_Normal_Red_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        internal static string Sure_CH {
            get {
                return ResourceManager.GetString("Sure_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string Sure_EN {
            get {
                return ResourceManager.GetString("Sure_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap TPLogo_Light {
            get {
                object obj = ResourceManager.GetObject("TPLogo_Light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 /n測試參數的配置需要更新/n是否同意更新？/n 的當地語系化字串。
        /// </summary>
        internal static string UpdateProfile_CN {
            get {
                return ResourceManager.GetString("UpdateProfile_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 /nThe specifications of the test items will be updated./nDo you want to update?/n 的當地語系化字串。
        /// </summary>
        internal static string UpdateProfile_EN {
            get {
                return ResourceManager.GetString("UpdateProfile_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 假如所有通道數量一樣，是否要保留原本的整面資料？(Uniformity、MicroOpen) 的當地語系化字串。
        /// </summary>
        internal static string UpdateProfileWarning_CN {
            get {
                return ResourceManager.GetString("UpdateProfileWarning_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 If all channels are the same, do you want to keep the adjusted frame data? (Uniformity、MicroOpen) 的當地語系化字串。
        /// </summary>
        internal static string UpdateProfileWarning_EN {
            get {
                return ResourceManager.GetString("UpdateProfileWarning_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap usb_icon {
            get {
                object obj = ResourceManager.GetObject("usb_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Wifi_1_icon {
            get {
                object obj = ResourceManager.GetObject("Wifi_1_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        internal static string Yes_CN {
            get {
                return ResourceManager.GetString("Yes_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yes 的當地語系化字串。
        /// </summary>
        internal static string Yes_EN {
            get {
                return ResourceManager.GetString("Yes_EN", resourceCulture);
            }
        }
    }
}
